on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:    
      - 'main'
      - 'learn/**'
    paths-ignore:
      - '**/README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: AzureLoginSample

jobs:
  StartVM:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true 
      
      #- name: 'Run Azure CLI commands'
      #  run: |
      #    az account show
      #    az group list
      #    pwd
      
      #- name: Azure PowerShell Action
      #  uses: Azure/powershell@v1
      #  with:
      #    inlineScript: Get-AzResourceGroup
      #    azPSVersion: "latest"
      
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: Start-AzVM -ResourceGroupName "sandbox" -Name "testgitactions"
          azPSVersion: "latest"
      
          
      #- name: Azure CLI script
      #  uses: Azure/CLI@v1
      #  with:
      #    azcliversion: 2.0.72
      #    inlineScript: |
      #        az account show
      #        az storage -h
  my_deploy:
    runs-on: self-hosted
    needs: [ StartVM ]
    steps:
      - name: Run a multi-line script
        run: |
          write-output "hello from $env:computername",
          $PWD

