on:
  workflow_dispatch:

name: examples-terraform-5-ssh

jobs:
  Terraform_apply:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
  
      #- name: 'Terraform Format'
      #  uses: hashicorp/terraform-github-actions@master
      #  with:
      #    tf_actions_version: 1.2.5
      #    tf_actions_subcommand: 'fmt'
      #    tf_actions_working_dir: "./terraform"

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.5
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./examples/terraform-5-ssh"
  
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.5
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./examples/terraform-5-ssh"

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.5
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./examples/terraform-5-ssh"
  
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.5
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./examples/terraform-5-ssh"
  
  #Terraform_destroy:
  #  env:
  #    ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  #    ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  #    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #    ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  #  runs-on: ubuntu-latest

        