on:
  workflow_dispatch:

name: examples-terraform-6-https-private

jobs:
  Terraform_apply:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      #- run: |
      #    cat <<EOF > creds
      #      #!/bin/sh
      #      echo protocol=https
      #      echo host=github.com
      #      echo username=foo
      #      echo password=${GH_TOKEN}
      #    EOF
      #    sudo install creds /usr/local/bin/creds
      #    git config --global credential.helper "creds"
      #  env:
      #    GH_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}
      - run: |
          git config --global url."https://oauth2:${{ secrets.GH_PRIVATE_TOKEN }}".insteadOf "https://github.com"
          git config --global -l
        #env:
        # GH_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}

      - run: |
          git config --global -l
      #- name: 'Terraform Format'
      #  uses: hashicorp/terraform-github-actions@master
      #  with:
      #    tf_actions_version: 1.2.5
      #    tf_actions_subcommand: 'fmt'
      #    tf_actions_working_dir: "./terraform"

      - name: 'Terraform Init'
        working-directory: ./examples/terraform-6-https-private
        run: |
          terraform init
  
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.5
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./examples/terraform-6-https-private"

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.5
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./examples/terraform-6-https-private"
  
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.5
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./examples/terraform-6-https-private"
  
  #Terraform_destroy:
  #  env:
  #    ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  #    ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  #    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #    ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  #  runs-on: ubuntu-latest