name: "workflow call example"
on:
  push:
    branches:    
      - 'feature/workflow_dispatch'

jobs:
  check-qa:
    uses: ./.github/workflows/blank.yaml
    with:
      build_id: build_from_call
      deploy_target: target_from_call
      perform_deploy: true
    secrets:
      access-token: ${{ github.ref }}